"""system_alerts — persist '🚨 SYSTEM' alerts so the HUD Activity feed can show them

Revision ID: 005_system_alerts
Revises: 004_audit_trail_latency
Create Date: 2026-06-23

failure_alerter.send_system_alert was Telegram-only + persisted nowhere; this
table lets the same alert ALSO appear in /api/activity as a recent warning. A
small dedicated store — NOT a reuse of audit_trail (that's tool-execution-shaped
and would fight the feed's _TOOL_MAP).

**Numbered 005 from disk** (001-004 present; latest is 004_audit_trail_latency).
Verified live that no `system_alerts` table existed before writing this
(`project_phase1_monolithic_migration.md` — disk is canonical). Hand-written, not
autogenerated, so there's no autogen drift to drop.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "005_system_alerts"
down_revision: str | Sequence[str] | None = "004_audit_trail_latency"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "system_alerts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_system_alerts_created_at", "system_alerts", ["created_at"])


def downgrade() -> None:
    op.drop_index("ix_system_alerts_created_at", table_name="system_alerts")
    op.drop_table("system_alerts")
