"""email_logs.provider — tag each email record with its EmailProvider

Revision ID: 006_email_log_provider
Revises: 005_system_alerts
Create Date: 2026-06-24

Makes the email record multi-provider-aware: which EmailProvider adapter the
message came through ("gmail" | "outlook" | …). server_default="gmail"
backfills every existing row (all of which are Gmail) and keeps the column
NOT NULL without a data-migration step. The `gmail_message_id` column name is
left as-is (historical) — it stores the OPAQUE provider message id regardless of
provider; a physical rename is a deferred cosmetic (its UNIQUE constraint is the
inbound dedup gate, so renaming it is higher-risk-lower-reward).

**Numbered 006 from disk** (001-005 present; latest is 005_system_alerts).
Hand-written (not autogenerated), so no autogen drift to drop.
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "006_email_log_provider"
down_revision: str | Sequence[str] | None = "005_system_alerts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "email_logs",
        sa.Column("provider", sa.String(length=20), nullable=False, server_default="gmail"),
    )


def downgrade() -> None:
    op.drop_column("email_logs", "provider")
