"""actionable_items — the actionable-memory foundation (Phase 4.1)

Revision ID: 007_actionable_items
Revises: 006_email_log_provider
Create Date: 2026-06-25

A NEW table (not in the 001 monolithic schema — verified absent via \\dt before
writing this). Open tasks the master needs to act on: mutable, queryable task
state (status / priority / due_date) that readiness intelligence (4.3) aggregates
over a time period. Distinct from pending_approvals (HITL gates) and Mem0
(immutable facts). Single source of truth for tasks — not mirrored into Mem0.

**Numbered 007 from disk** (001-006 present; latest head is 006_email_log_provider).
Hand-written (not autogenerated). Composite indexes match the readiness query
paths: (status, due_date) for "open tasks due in [period]", (status, priority)
for the priority-scaled look-ahead.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "007_actionable_items"
down_revision: str | Sequence[str] | None = "006_email_log_provider"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "actionable_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="open"),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", postgresql.JSONB(), nullable=False, server_default="{}"),
    )
    op.create_index("ix_actionable_items_status", "actionable_items", ["status"])
    op.create_index("ix_actionable_items_due_date", "actionable_items", ["due_date"])
    op.create_index("ix_actionable_items_created_at", "actionable_items", ["created_at"])
    op.create_index(
        "ix_actionable_items_status_due", "actionable_items", ["status", "due_date"]
    )
    op.create_index(
        "ix_actionable_items_status_priority", "actionable_items", ["status", "priority"]
    )


def downgrade() -> None:
    op.drop_table("actionable_items")
