"""user_profiles.briefing_hwm — the read-state briefing high-water mark (Phase 5.1)

Revision ID: 008_briefing_hwm
Revises: 007_actionable_items
Create Date: 2026-06-25

The per-master "heard-up-to" mark: "latest" = briefing_items in (briefing_hwm, now],
then advance it (atomic + monotonic). NULLABLE — NULL until the first briefing (5.2
floors a NULL HWM at now−24h). A plain typed column on the single-row profile (NOT
in always_on/on_demand, so it never enters the prompt) — leaner than a one-row
state table for a single per-master scalar.

**Numbered 008 from disk** (001-007 present; latest head is 007_actionable_items).
Hand-written (not autogenerated).
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "008_briefing_hwm"
down_revision: str | Sequence[str] | None = "007_actionable_items"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "user_profiles",
        sa.Column("briefing_hwm", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("user_profiles", "briefing_hwm")
